"""fill database

Revision ID: 1032806a1bdb
Revises: 6f6ddd01e29c
Create Date: 2025-11-10 07:49:22.302796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1032806a1bdb"
down_revision: Union[str, Sequence[str], None] = "6f6ddd01e29c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Заполняем таблицу incidents тестовыми данными
    op.execute("""
        INSERT INTO incidents (status, source, description, creating_date) VALUES
        ('new', 'operator', 'Пользователь сообщил о проблеме с авторизацией в системе', NOW() - INTERVAL '2 hours'),
        ('new', 'monitoring', 'Обнаружено превышение нагрузки на сервер БД', NOW() - INTERVAL '1 hour'),
        ('in_progress', 'web', 'Ошибка 404 на главной странице сайта', NOW() - INTERVAL '3 hours'),
        ('in_progress', 'api', 'Медленный ответ API endpoint /users', NOW() - INTERVAL '4 hours'),
        ('resolved', 'user', 'Не работает кнопка сохранения в форме', NOW() - INTERVAL '1 day'),
        ('resolved', 'mobile', 'Приложение вылетает при открытии профиля', NOW() - INTERVAL '2 days'),
        ('closed', 'partner', 'Интеграция с партнерской системой не отвечает', NOW() - INTERVAL '3 days'),
        ('closed', 'system', 'Автоматическое резервное копирование завершилось с ошибкой', NOW() - INTERVAL '4 days'),
        ('canceled', 'operator', 'Дубликат запроса #1234', NOW() - INTERVAL '5 days'),
        ('new', 'monitoring', 'Высокое использование памяти на сервере app-01', NOW() - INTERVAL '30 minutes'),
        ('in_progress', 'user', 'Не приходят уведомления на email', NOW() - INTERVAL '6 hours'),
        ('resolved', 'web', 'Некорректное отображение таблицы в Chrome', NOW() - INTERVAL '1 week'),
        ('new', 'api', 'Rate limit превышен для endpoint /search', NOW() - INTERVAL '15 minutes'),
        ('in_progress', 'system', 'Ошибка синхронизации данных между микросервисами', NOW() - INTERVAL '8 hours'),
        ('closed', 'other', 'Плановые технические работы завершены', NOW() - INTERVAL '2 weeks')
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Очищаем тестовые данные из таблицы incidents
    op.execute("TRUNCATE TABLE incidents RESTART IDENTITY CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
