"""init

Revision ID: 709515793a76
Revises: 
Create Date: 2025-11-10 07:43:35.710556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709515793a76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'resolved', 'closed', 'canceled', name='incidentstatusenum'), nullable=False),
    sa.Column('source', sa.Enum('operator', 'monitoring', 'partner', 'system', 'user', 'api', 'web', 'mobile', 'other', name='incidentsourceenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('creating_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # Удаляем ENUM типы
    op.execute("DROP TYPE IF EXISTS incidentsourceenum")
    op.execute("DROP TYPE IF EXISTS incidentstatusenum")
    # ### end Alembic commands ###
