"""empty message

Revision ID: b1d43ad5f2f6
Revises: 1032806a1bdb
Create Date: 2025-11-10 07:57:14.226323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1d43ad5f2f6"
down_revision: Union[str, Sequence[str], None] = "1032806a1bdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "incidents", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "incidents", type_="unique")
    # ### end Alembic commands ###
